name: Build and Push to Docker Registry

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
  
  pull_request:
    types:
      - closed
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a three jobs called "test_app", "build", "push_on_docker"
  
  docker:
    if_merged:
      if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/karpatkey/defi-presets
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}
            latest


      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build and Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile

  update-deployment:
    needs: docker
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: kubectl delete pod -n karpatkey-defi-presets -l app=karpatkey-defi-presets --force