name: Check for protocol updates

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIG_PATH: ${{ github.workspace }}/scripts/config.json
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: setup config file
        run: |
          echo $POSTGRESQL_HOST >> $CONFIG_PATH

      - name: install python packages
        run: |
          cd scripts 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run aave.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}

      - name: run prettier
        run: |
          cd ..
          yarn
          yarn fix:prettier

      - name: create pr
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: protocol updates
          title: "[nightly] Protocol updates"
          body: >
            The nightly job detected updates to the protocol configs
          labels: bot
          branch: protocol-updates
